### ISSUE TITLE
Fix the race condition with Dialog tests

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/ios-sdk#113]
Ensure that Dialog tests always pass!

**Comment by glennrfisher** [comment]
I haven't seen this error since switching to `WatsonGateway` for networking. With #130, though, my hunch is that the extra networking calls are providing enough time for things to settle.

We should check for this race condition again after #130 is resolved. If it reappears, then we can add a sleep statement to wait a couple seconds after a Dialog application is created.

**Comment by vherrin** [comment]
I have not seen this error either.  I will add a 3 sec delay just after create as a preventative and close out this ticket.
