### ISSUE TITLE
Map arrays using ObjectMapper

### ISSUE THREAD

**Issue by vherrin** [watson-developer-cloud/ios-sdk#117]
As a developer, I do not want to iterate through the response but have helpers such as ObjectMapper to populate the array for me.  This will simplify the code size and readability. 

Example 

***Before***

            var languages : [IdentifiableLanguage] = []
            
            if case let data as Dictionary<String,AnyObject> = response.data {
                if case let rawLanguages as [AnyObject] = data[LanguageTranslationConstants.languages] {
                    for rawLanguage in rawLanguages {
                        if let language = Mapper<IdentifiableLanguage>().map(rawLanguage) {
                            languages.append(language)
                        }
                    }
                }
            }

***After***

    let languages = Mapper<Language>().mapArray(data, keyPath: "languages")

**Comment by glennrfisher** [comment]
This is no longer relevant given our migration to Alamofire and Freddy in the `rest-kit` branch.
