### ISSUE TITLE
Create a simpler translate method

### ISSUE THREAD

**Issue by rfdickerson** [watson-developer-cloud/ios-sdk#118]
Currently, the Translate method takes an array of Strings and returns an array of Strings. It might be easier for our users (in the assumed use case) to simply provide a String and return a String.

Take the current:

```swift
public func translate(text: [String], source: String, target: String,
        completionHandler: ([String]?, NSError?) -> ()) {
```

and add:

```swift
public func translate(text: String, source: String, target: String,
        completionHandler: (String?, NSError?) -> ()) {
```

**Comment by glennrfisher** [comment]
Ready for acceptance with 197125d4d800d0543e4abfb499622820fa2812f7
