### ISSUE TITLE
Add support for Swift Package Manager

### ISSUE THREAD

**Issue by kweinmeister** [watson-developer-cloud/ios-sdk#120]

**Comment by glennrfisher** [comment]
This is easiest for us to tackle on the `rest-kit` branch.

1. Use `swift build --init` to create the directory structure.
2. Update `Package.swift` to reflect name, dependencies, and targets.
3. Migrate the code to the new directory structure.

**Comment by glennrfisher** [comment]
An initial `Package.swift` file was created with the v0.3.0 release, but we still need to add targets and test it with the Swift Package Manager.

**Comment by glennrfisher** [comment]
Targets were added with #282. However, we will keep this ticket open until the release of Swift 3 when we can test it. (The Swift Package Manager has not been included in recent builds of Swift 2.2.)
