### ISSUE TITLE
Add support for Objective-C

### ISSUE THREAD

**Issue by kweinmeister** [watson-developer-cloud/ios-sdk#123]
* [ ] Extend NSObject
* [ ] Add documentation for using in an Objective-C project
* [ ] Update README to refer to Swift *and Objective-C* applications

**Comment by FatCharlie** [comment]
What's the word on this ?

How would I go about trying to do this on my own, what is supposed to extend NSObject, etc ?

**Comment by ruslan120101** [comment]
This should be a fairly straightforward step. Making all aspects of this API available from Objective C will only require 
* NSObject inheritance
* ```@objc``` markers 
where such functionality is desired

[Source](http://stackoverflow.com/questions/31099596/importing-swift-framework-into-a-objective-c-project)

**Comment by glennrfisher** [comment]
I'm going to close this issue. We'll be embracing Swift moving forward--especially open source Swift and Swift 3.0. By dropping explicit bridging support to Objective-C, we can better embrace Swifty conventions.

We understand that many legacy apps are still using Objective-C, but may want to use this SDK. In these situations, it is best to take advantage of the ability to mix Swift and Objective-C code in the same project.
