### ISSUE TITLE
Discover why carthage pull and build fails occasionally 

### ISSUE THREAD

**Issue by vherrin** [watson-developer-cloud/ios-sdk#124]
Carthage on occasion can fail to build when using carthage update.  This does not occur every time

**Comment by glennrfisher** [comment]
Some references that might be helpful for the build failures:
- [Carthage Issue #399](https://github.com/Carthage/Carthage/issues/399#issuecomment-86089516)
- [Carthage Issue #281](https://github.com/Carthage/Carthage/issues/281)
- [StackOverflow Question on Code Signing](http://stackoverflow.com/questions/30963294/creating-ios-osx-frameworks-is-it-necessary-to-codesign-them-before-distributin)

Some references that might be helpful for the `lipo` tool warnings:
- [lipo man page](http://www.manpages.info/macosx/lipo.1.html)

**Comment by vherrin** [comment]
I've been testing this out with no errors after many rebuilds.  This includes running carthage for SDK and getting started app.  One thing I did do was update to the latest Carthage of v0.11 and that might have some impact.  I will close this out if no issues found by the end of the day

**Comment by vherrin** [comment]
Ok still no errors so closing out.  Please note the readme now contains the recommended version of 0.11 for Carthage
