### ISSUE TITLE
App crash on startListening() method

### ISSUE THREAD

**Issue by Dhvl-Golakiya** [watson-developer-cloud/ios-sdk#146]
Hi, 
In past, I were using SpeechToText.transcribe() method for converting speech to Text and it was working fine. But now I'm using SpeechToText.startListening() method for that . But when this method call, X-code crash and I'm getting EXC_BAD_ACCESS error.

``Exception Type:        EXC_BAD_ACCESS (SIGSEGV)``
``Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000``
``Exception Note:        EXC_CORPSE_NOTIFY
``

**Comment by glennrfisher** [comment]
Hi @Dhvl-Golakiya,

Thanks for letting us know about the bug! We are still hard-at-work to add support for continuous listening with SpeechToText. (Let me tag @rfdickerson, who has been spearheading that service.)

Unfortunately, the `startListening` function is not yet ready for consumption—perhaps we shouldn't even have exposed it in our latest release. I believe we're aiming to support continuous listening for our next milestone release at the end of January.

Sorry we couldn't have better news for you, but it's great to have you using our SDK and exposing these sorts of bugs. We would love your feedback as you continue working with the SDK. And please let us know if there's anything we can do to help get you up-and-running!

**Comment by glennrfisher** [comment]
FYI I opened issue #147 to help us track the implementation of continuous listening and the `startListening` function.

**Comment by dsato80** [comment]
I found a bug in 
https://github.com/watson-developer-cloud/ios-sdk/blob/master/WatsonDeveloperCloud/SpeechToText/SpeechToText.swift#L126-L140

`if var audioState = audioState {`
this statement copies self.audioState struct **value** to temporal audioState variable.
It causes EXC_BAD_ACCESS error because temporal variable is released when `startListening` is returned.

**Comment by glennrfisher** [comment]
Ah, great catch @dsato80! Value versus class semantics can sometimes be very subtle and challenging to debug.

I also created a quick playground to verify and demonstrate that behavior:

<img width="961" alt="screen shot 2016-01-06 at 10 18 11 pm" src="https://cloud.githubusercontent.com/assets/1957636/12162271/2e497c1e-b4c5-11e5-90c0-0789caed0d40.png">
