### ISSUE TITLE
[speech-to-text] Add support for continuous listening

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/ios-sdk#147]
Finish implementing and testing the `SpeechToText.startListening` function.

**Comment by mitulgolakiya** [comment]
+1

**Comment by dladouceur** [comment]
Holding up our production release.
We can help in any way.

**Comment by rfdickerson** [comment]
Hi @dladouceur , we have continuous listening on our roadmap for beta release 0.2.0. The roadblock we are facing is that the Ogg library will not successfully packetize our compressed PCM audio. Using the PCM + OGG formats have decreased the audio sizes by at least 1/5.

In order to get continuous listening working while we figure out the issue about the OGG packets will be to simply stream through the WebSocket the PCM data captured. We will use the callback delegate you have found for returning progress.

**Comment by dsato80** [comment]
+1

I also want to use continuous listening and want to request some additional functionality.
Issue is the right place to put my requests?

**Comment by glennrfisher** [comment]
@dsato80: Yup! We have good visibility across our team for Github issues. If you'd like to request any additional functionality, please feel free to open an issue. We'll start a conversation and add it to our backlog. Looking forward to hearing your thoughts!

Feel free to submit pull requests, as well, if you'd like to dive into the code.

**Comment by glennrfisher** [comment]
Copying @dsato80's excellent bug note from #146 for future reference here:

> I found a bug in 
https://github.com/watson-developer-cloud/ios-sdk/blob/master/WatsonDeveloperCloud/SpeechToText/SpeechToText.swift#L126-L140

> if var audioState = audioState {
this statement copies self.audioState struct value to temporal audioState variable.
It causes EXC_BAD_ACCESS error because temporal variable is released when startListening is returned.

**Comment by dsato80** [comment]
It is very helpful that I can prepare websocket connection before startListening.
For example `SpeechToText.connect(completionHandler)`
Currently the websocket connection takes a few seconds, it is critical for speech dialog system with STT.

* SpeechToText.connect(completionHandler)
* SpeechToText.disconnect(completionHandler)
* SpeechToText.startListening()
* SpeechToText.stopListening()

It is also helpful that I can send no-op message to prevent service timeout.
https://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/speech-to-text/using.shtml#timeouts
> When using the WebSocket protocol, you can send a message with no-op as the action to keep the session alive.

**Comment by dladouceur** [comment]
This example requires a client "stop" and there is no way for we can detect silence on IOS ? So how can I know when to send "STOP". Please advise how to get final packet without the STOP or waiting 30 seconds?

In the third example, the client again sends audio that contains the string Name the Mayflower. As with the first example, the client sends the audio in two chunks in PCM format. This time, the client asks the server to send interim results for the transcription. 
Client>> {"action": "start", "content-type": "audio/l16;rate=22050", "interim_results": true}
Server<< {"state":"listening"}
Client>> <audio data chunk>
Server<< {"results": [{"alternatives": [{"transcript": "name "}],"final": false}],"result_index": 0}
Server<< {"results": [{"alternatives": [{"transcript": "name may "}],"final": false}],"result_index": 0}
Client>> <audio data chunk>
Client>> {"action": "stop"}
Server<< {"results": [{"alternatives": [{"transcript": "name may flour "}],"final": false}],"result_index": 0}
Server<< {"results": [{"alternatives": [{"transcript": "name the mayflower "}],"final": true}],"result_index": 0}
Server<< {"state":"listening"}

**Comment by dsato80** [comment]
I think this is just [an example](https://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/speech-to-text/websockets.shtml#WSexample) of STT API.
You can send STOP when you get the final result. The service detects the end of the phrase.
We need to dig into raw audio data to get silence on iOS. #152 
> By default, the service stops transcription at the first pause, which is denoted by a half-second of non-speech (typically silence), or when the stream terminates. This is referred to as an end of speech (EOS) incident.


Client>> {"action": "start", "content-type": "audio/l16;rate=22050", "interim_results": true}
Server<< {"state":"listening"}
Client>> 
Server<< {"results": [{"alternatives": [{"transcript": "name "}],"final": false}],"result_index": 0}
Server<< {"results": [{"alternatives": [{"transcript": "name may "}],"final": false}],"result_index": 0}
Client>> 
Server<< {"results": [{"alternatives": [{"transcript": "name may flour "}],"final": false}],"result_index": 0}
Server<< {"results": [{"alternatives": [{"transcript": "name the mayflower "}],"final": true}],"result_index": 0}
Client>> {"action": "stop"} <--------------------------
Server<< {"state":"listening"}

**Comment by mitulgolakiya** [comment]
Hi, this is Mitul Golakiya from Neon Mobile, as @dladouceur mentioned above, we are using your SDK and trying to implement continuous listening for our production release. so we did some changes to current library like,

- passing interim_results true
- Do not write action=stop just after writing data chunk on socket (https://github.com/watson-developer-cloud/ios-sdk/blob/master/WatsonDeveloperCloud/SpeechToText/WatsonSocket.swift#L244).
- Implemented continuous listening by using one third party class (AudioProcessor) which is doing all streaming stuff etc.

Here is the full process that we are doing:

1. call WatsonSocket.connectWebsocket() method to connect a socket (we made one custom method for it - WatsonSocket.sendContinuous())

2. Just after that, Start adding captured data to audioUploadQueue (but it will be suspended till we are not connected to IBM WebSocket)

3. Once web socket is connected and authenticated, queue will be set to suspended=false (SDK is already doing it)

4. By making suspended=false data queue will start uploading data

Everything is working fine till now, but by this process, sometimes we are getting results and sometimes not. And even if we stop speaking, we are not getting final=true. You mentioned above that, "The service detects the end of the phrase". But it's not. We are getting interim results but not getting final flag true. Socket waits for 30 seconds and does a timeout.

[Here](https://www.dropbox.com/s/7ck71qnhcxmo1rd/Neon%20IBM%20Watson%20STT.zip?dl=0) is all modified SDK files as well as our project files. Can you let us know if we are missing anything ?

**Comment by dsato80** [comment]
Hi mitulgolakiya

The data buffer is allocated by the system and might be freed after adding to the queue.
I think, you need to copy the buffer data for the queue.

```objective-c
self.stt.appendData(data.copy() as! NSData)
```

The code includes your credential. So I recommend you to change the credential.

**Comment by mitulgolakiya** [comment]
@dsato80  This solution is working and now we are getting final flag true with proper recognized text. Thanks.

**Comment by glennrfisher** [comment]
We've been asked to redesign the API for SpeechToText and will be looking at it next week. We will probably write the service from scratch, but will draw from existing code and tests in the process.

We expect this to be a breaking change that will require client code to be modified. We'd love to get all of your feedback, though, after we push the updates!

**Comment by glennrfisher** [comment]
Closed in favor of #168.
