### ISSUE TITLE
Update error handling for consistency across services

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/ios-sdk#150]
What error code should be returned for an internal consistency error?

For example, we use a `weak` reference to `self` in `WatsonGateway`. We do not expect `self` to be nil, but we should (and are required by Swift) to check that `self` is not nil. See the code below for an example.

What error code should we return in situations like these? If it occurred on the server, we could return a `500` error. Since this occurs on the client, however, we should use a unique error code.

```swift
let cachedRequest = { [weak self] in
    guard let strongSelf = self else {
        let code = -1
        let description = "Internal error. Unable to execute network operation."
        let error = NSError.createWatsonError(code, description: description)
        completionHandler(nil, error)
        return
    }
    ...
}
```

**Comment by glennrfisher** [comment]
@germanattanasio Are there any standard error codes that you used in the Java or Node SDKs?

**Comment by jsstylos** [comment]
We haven't been returning error codes for internal errors -- an error in our SDKs manifest themselves in the form of language-native exceptions that don't look like the error responses from the service and so don't have a code field. We probably want to avoid using REST codes in the SDK errors to avoid the impression that the request made it all the way to the server.

**Comment by glennrfisher** [comment]
Okay. In that case, we should probably use the `kCFURLErrorUnknown` (-998) or `NSURLErrorCancelled` (-999) error codes, depending on the context. -- [NSError](http://nshipster.com/nserror/).

**Comment by glennrfisher** [comment]
This has been addressed in the `rest-kit` branch. In particular, we've been using `0` for all internal errors caught by the SDK.
