### ISSUE TITLE
testCreateModel method crashing test execution when using Bluemix trial account

### ISSUE THREAD

**Issue by lucasdamiani** [watson-developer-cloud/ios-sdk#153]
If you run the test *LanguageTranslationTests.testCreateModel()* using a Bluemix trial account, the test should fail gracefully. Trial accounts aren't allowed to create models (Error message: Code=403 "supplied bluemix-plan-id does not permit access to customization"). 
However, instead of failing, the whole test execution crashes, stopping the execution of remaining tests. 

<img width="1123" alt="screen shot 2016-01-05 at 17 53 21" src="https://cloud.githubusercontent.com/assets/10780674/12125910/5014bd72-b3d5-11e5-84d9-12fd972433a3.png">

To reproduce the error, you should:
* Create a Bluemix trial account
* Create the credentials to use the Language Translation API
* Configure Credentials.plist
* Run the *testCreateModel()*, on *LanguageTranslationTests* class

**Comment by glennrfisher** [comment]
Resolved with Lucas's PR #155 and commit ad529ae15ed109f0bdf0773f90b4bdcd78cac4bc to update the style.
