### ISSUE TITLE
Set `continueAfterFailure` to false for all tests

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/ios-sdk#157]
When writing the tests, we assumed that `XCTAssertNotNil(_:)` and `XCTAssertNil(_:)` statements would cause tests to fail. Instead, the test continues execution, which can cause later force unwrapped variables to crash the test instead of failing gracefully.

We should take another look at how we write our tests. Perhaps instead of something like:

```swift
service.createModel("en-es", name: "custom-english-to-spanish", fileKey: "forced_glossary", fileURL: fileURL!) { model, error in
            
    XCTAssertNotNil(model, "Expected non-nil model to be returned.")
    Log.sharedLogger.error("\(error)")
    creationExpectation.fulfill()
    
    // Add a small delay so the model is ready for delete.  This is not a normal flow of create and delete immediately
    // so this is only a testing issue
    sleep(3)
    
    self.service.deleteModel(model!) { error in
        XCTAssertNil(error)
        deletionExpectation.fulfill()
    }
}
```

we should follow good practices and style with something like this instead:

```swift
service.createModel("en-es", name: "custom-english-to-spanish", fileKey: "forced_glossary", fileURL: fileURL!) { model, error in

    guard let model = model else {
        XCTFail("Expected non-nil model. Please upgrade your Language " +
            "Translation Service to the \"Trainable\" plan.")
        creationExpectation.fulfill()
        deletionExpectation.fulfill()
        return
    }

    guard error == nil else {
        XCTFail("Expected nil error.")
        Log.sharedLogger.error("\(error)")
        creationExpectation.fulfill()
        deletionExpectation.fulfill()
        return
    }
    
    creationExpectation.fulfill()
    
    // Add a small delay so the model is ready for delete.  This is not a normal flow of create and delete immediately
    // so this is only a testing issue
    sleep(3)
    
    self.service.deleteModel(model) { error in
        XCTAssertNil(error)
        deletionExpectation.fulfill()
    }
}
```

**Comment by glennrfisher** [comment]
As Lucas demonstrated in #161, we can set the `continueAfterFailure` property to `false` to cause tests to immediately fail whenever an assert is not satisfied. We should update all tests to configure the `continueAfterFailure` property in the `setUp` function. (While we're at it, we can update the tests to always create a new service in the `setUp`.)

**Comment by glennrfisher** [comment]
One more gotcha: according to [this bug report](http://www.openradar.me/18110715) the `XCTAssert` and `XCTAssertNotNil` functions do not work with Swift structs.

So we will probably want to use an alternative check:

`XCTAssert(results != nil)`
`XCTAssert(error == nil)`

or

`guard let results = results else { XCTFail() }`
`guard error != nil else { XCTFail() }`

**Comment by vherrin** [comment]
Lets check if swift 2.2 fixes the issue!

**Comment by vherrin** [comment]
That bug report is with xcode version 6.  I tested this with xcode 7 and swift 2.1 with no issues.  I must be missing something here.

**Comment by glennrfisher** [comment]
We have been careful to set `continueAfterFailure = false` in the `setUp` method of all tests in the `rest-kit` branch.
