### ISSUE TITLE
[speech-to-text] Save sent audio as file

### ISSUE THREAD

**Issue by dsato80** [watson-developer-cloud/ios-sdk#159]
I want to save sent audio as file. (WAV or OGG format with customizable name)
The audio file starts at startListening and ends at stopListening.

If raw data callback is provided, I can implement it by myself.
https://github.com/watson-developer-cloud/ios-sdk/issues/152#issuecomment-169542020

**Comment by glennrfisher** [comment]
Closed in favor of #168.
