### ISSUE TITLE
[dialog] Create test for duplicate Dialog names

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/ios-sdk#160]
Dialog application names must be globally unique. If there is a name conflict, then a 409 error is returned.

We should write a test that tries to create a Dialog with a conflicting name and ensure that the 409 error is propagated back to the user.

<img width="950" alt="screen shot 2016-01-08 at 5 05 24 pm" src="https://cloud.githubusercontent.com/assets/1957636/12211972/cfa66912-b62a-11e5-9a9d-6c2ef1161676.png">

**Comment by lucasdamiani** [comment]
I've encountered this issue as well. However, when I face the error code 409, Xcode crashes due to EXC_BAD_ACCESS (probably due to unwrapping nil objects). I couldn't find the root cause yet, but I have a few hypothesis (Xcode bug, thread sync problem, etc). Are you facing the EXC_BAD_ACCESS error as well?

**Comment by glennrfisher** [comment]
Yes, I ran into the same bug you described today while running tests for a pull request. Since dialog application names must be globally unique, other people executing the tests have already created a "pizza-watsonsdk-ios" dialog application, causing a name conflict when we execute the tests.

We need to update the tests to:
1. Handle name conflicts with a more graceful error (your `continueAfterFailure = false` solutions should work here).
2. Generate a unique dialog application name for each test execution.

**Comment by glennrfisher** [comment]
See #160 for reference.

**Comment by glennrfisher** [comment]
This test is included in the `rest-kit` branch. It returns an error, as expected, instead of crashing due to forced unwrapping.
