### ISSUE TITLE
[natural-language-classifier] testClassifyWithTrainedClassifier crashing test execution when not possible to create classifiers

### ISSUE THREAD

**Issue by lucasdamiani** [watson-developer-cloud/ios-sdk#162]
If you run the unit tests *testClassifyWithTrainedClassifier()*, and you're not allowed to create new classifier (Error 400, 8 classifiers maximum when using Bluemix trail account), the test execution crashes due to EXC_BAD_INSTRUCTION, stopping the execution of the remaining tests. 

<img width="1261" alt="screen shot 2016-01-13 at 11 23 09" src="https://cloud.githubusercontent.com/assets/10780674/12295426/3025ac06-b9e8-11e5-88e9-713dd413d6b6.png">

To reproduce the error you should:
1. Create a Bluemix trial account
2. Create the credentials to use the Natural Language Classifier API
3. Configure Credentials.plist
4. Create 8 classifiers using the NLC API
5. Run the testClassifyWithTrainedClassifier(), on *NaturalLanguageClassifierTests* class

**Comment by glennrfisher** [comment]
This issue is fixed in the `rest-kit` branch, where we:
1. No longer need to force-unwrap the classifier, given the separate `success` and `failure` closures.
2. Set `continueAfterFailure = false`.
