### ISSUE TITLE
Terms of service ? 

### ISSUE THREAD

**Issue by johnmci** [watson-developer-cloud/ios-sdk#163]
Buried in http://www-03.ibm.com/software/sla/sladb.nsf/sla/bm-6945-01?Open

The Cloud Service can be used for development of applications that may only be used internally within 
Client’s enterprise

But that seems to preclude distribution of an app thru the App Store for use by the public? Please advise

**Comment by glennrfisher** [comment]
@jsstylos, @vherrin, @germanattanasio: Who could we contact to get an answer to this question?

**Comment by glennrfisher** [comment]
Any ideas, @jsstylos, @germanattanasio, or @vherrin?

**Comment by mbouldin** [comment]
There are different routes to the WDC services.  Via Bluemix they're limited to Enterprise customers to develop internal Enterprise apps, and it's pay as you go.  Via the Ecosystem members they're available to develop apps intended to be sold to customers and it's a revenue share model.  The best information on this appears to be located here -> https://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/solutions.html.

**Comment by vherrin** [comment]
An update to the Terms of Service with the following information related to this ticket

http://link2-em-us.unicaondemand.com/frontend/dynamicAssets?e=t7D817B2A97BFDA7CC297B096E5DE839B14DB35C26F75109F888D90E7BE4B67FE17BA3BE7CD1DAD596EF29B52AF098C49A36158FDD5BB7771EAA49B82AF2F1C3C4ADEA7E888AF3EF5DA087CC57C7087C5F4C13C563393ACD51AEFBFF9B0229DB3502FDA80BA565411


Hi, Watson Developer Cloud Services on Bluemix User:

We're happy to inform you that we're making changes to the Service Descriptions for many of the Generally Available Watson Developer Cloud Services on Bluemix. These changes are intended to make our services easier to use.

Specifically, we are lifting previous restrictions for the use of Watson APIs in commercial applications. The below clause will be removed from the Service Descriptions:

"The Cloud Service may only be used for development of applications for internal use within the Client's Enterprise."

Please note this update will go into effect 30 days from the date this email is sent.
