### ISSUE TITLE
Support model parameter on Speech To Text API

### ISSUE THREAD

**Issue by lucasdamiani** [watson-developer-cloud/ios-sdk#166]
When transcribing a speech in a language other than english, you have to send the model parameter to the recognize method, specifying the language that you want to transcribe text from. 

https://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/speech-to-text/using.shtml#models

The SDK should provide a method to specify the model that you want to use to transcribe the audio.

**Comment by glennrfisher** [comment]
Supported with PR #158.
