### ISSUE TITLE
Transcode audio to Opus

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/ios-sdk#175]
When redesigning the implementation of SpeechToText, we decided to focus on WAV support first. However, @rfdickerson found that we could *dramatically* improve performance by compressing the audio before sending it to the Speech to Text service.

We should look into compressing the streaming microphone audio before sending it to the service. Opus is a good candidate.

#### Related Issues

- #138
- #108
- #183

**Comment by glennrfisher** [comment]
See #138 and #108.

**Comment by rfdickerson** [comment]
Another option would be to allow for additional codecs on the backend so that it can decompress AAC, MP3, etc.

**Comment by glennrfisher** [comment]
Complete in the `speech-to-text` branch.
