### ISSUE TITLE
Create an AVCaptureInput implementation to read from an audio file

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/ios-sdk#180]
Since the simulator does not provide access to the microphone, this would allow us to use continuous integration tests for the streaming functionality of Speech to Text.

**Comment by rfdickerson** [comment]
This would be awesome!

**Comment by glennrfisher** [comment]
We are moving to audio queues instead of AVCaptureSession (see #404), so this issue is no longer relevant.

**Comment by dake** [comment]
Hi, if Anyone knows how to create an AVCaptureInput implementation to read data from file, tell me, plz. That will be appreciate !!!

**Comment by glennrfisher** [comment]
We haven't spent too much time exploring this problem (and will probably skirt around it by using [audio queues](https://developer.apple.com/library/mac/documentation/MusicAudio/Conceptual/AudioQueueProgrammingGuide/Introduction/Introduction.html) instead of an `AVCaptureSession`), but every time we looked we haven't been able to find anything. :(
