### ISSUE TITLE
Visual Recognition in ios-sdk

### ISSUE THREAD

**Issue by mattdotmac** [watson-developer-cloud/ios-sdk#189]
Are there any plans to add visual recognition to the ios-sdk? It has been announced that [AlchemyVision and Visual Recognition services will be merging capabilities in early 2016](https://developer.ibm.com/watson/blog/2015/12/02/enabling-ibm-watson-to-see/), so perhaps it will be added then?

**Comment by glennrfisher** [comment]
Hi @mattdotmac!

The team is having a planning meeting on Tuesday (3/15/2016) to discuss the SDK and how to proceed after this month's 1.0 release. Unfortunately, I don't have any specifics for you at the moment, but I can at least give some insight into our priorities.

Right now our focus is to lay a strong foundation--we want to define the coding patterns and best practices for this SDK using the eight services that are currently implemented. Once that foundation is firmly in place, it will be easier to add support for additional services.

So be on the lookout for new services after the 1.0 release! :)

Also, it's great to hear your input. It's really valuable for us to learn what our users want. That helps us to prioritize the right work. Thanks!

**Comment by luish** [comment]
It would be great if we had those new services added to the framework. Please let us know about the plans on that, if possible. I'd be glad to be able to contribute with it. :)
