### ISSUE TITLE
Text to Speech fails with 'Code=400 No JSON object could be decoded'

### ISSUE THREAD

**Issue by teddynewell** [watson-developer-cloud/ios-sdk#193]
Looking forward to trying out text-to-speech and speech-to-text for potential use in a new app, but ran into a problem with the QuickStart example.  It's the same issue described in this [developerWorks question: "Watson texttospeech Code=400 No JSON object could be decoded - no sound played by app"](https://developer.ibm.com/answers/questions/256894/watson-texttospeech-code400-no-json-object-could-b/).  

I have a theory it may be due to the `contentType: .JSON` in the `WatsonRequest` created in `TextToSpeech().synthesize(_:voice:completionHandler:)`, since no content (JSON or otherwise) is added to the http message body.

**Comment by glennrfisher** [comment]
Thanks @teddynewell. Let's continue the conversation in the pull request.

Just an FYI, we're doing some heavy work on Speech to Text (see #187). It's _almost_ ready--though I keep saying that and then finding subtle bugs.

Let's stay in touch about your app. Don't hesitate to reach out if you have any questions, feature requests, bugs, or comments!
