### ISSUE TITLE
Issue with iOS-SDK AlchemyAPI

### ISSUE THREAD

**Issue by LinZhao1** [watson-developer-cloud/ios-sdk#197]
I tried to use keyword extraction to extract keyword, but there is one parameter I need is "sentiment = 1" by default is 0. After checking sdk code I found after WatsonDeveloperCloud SDK build, some values are missing for http parameters. Below are the screens. So in the end I call AlchemyAPI Rest API instead.

1. Struct is empty no parameters <br/>
![empty getkeywordparameters struct](https://cloud.githubusercontent.com/assets/16919559/13700500/10f08a90-e779-11e5-9f0b-8d6e594048e2.png)

2. In git master there are parameters<br/>
![parameters in master](https://cloud.githubusercontent.com/assets/16919559/13700508/17ca12c8-e779-11e5-8bb8-3a47390a7a44.png)

3. My code sample where I need set the parameters<br/>
![code where has the issue](https://cloud.githubusercontent.com/assets/16919559/13700513/1aba6b90-e779-11e5-915c-4bbefd40f74d.png)

**Comment by glennrfisher** [comment]
Hi @LinZhao1. Sorry to hear about the bug!

I [committed a fix](https://github.com/watson-developer-cloud/ios-sdk/commit/6299a03dfaf4f4fdd0c97a3f6947a891cd45ca91) to the [`remove-testable-annotation` branch](https://github.com/watson-developer-cloud/ios-sdk/tree/remove-testable-annotation), which will be merged into master as soon as [this pull request](https://github.com/watson-developer-cloud/ios-sdk/pull/187) is complete.

Unfortunately, our branching model has slowed down our ability to push quick fixes. We're going to change that very soon so we can respond quicker to bugs like this.
