### ISSUE TITLE
Add issue and pull request templates

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/ios-sdk#200]
I think that we need to take advantage of the new [issue template](https://github.com/blog/2111-issue-and-pull-request-templates) feature in GitHub. This will allow us to get more information from users when they are reporting issues. Specially the xcode, sdk and ios version they are using.

**Comment by germanattanasio** [comment]
@glennrfisher take a look and let me know if the templates are good enough.

**Comment by germanattanasio** [comment]
I just realized that I pushed to `master`. Sorry.. I will create a branch and open a pull request next time :disappointed:

**Comment by glennrfisher** [comment]
Great idea! I'll take a look this afternoon.

**Comment by vherrin** [comment]
Agreed great idea.  Also, there is some text about a special folder 

If you're worried about the added clutter in the root directory of your project, we also added support for a .github/ folder. You can put CONTRIBUTING.md, ISSUE_TEMPLATE.md, and PULL_REQUEST_TEMPLATE.md files in .github/ and everything will work as expected.

**Comment by germanattanasio** [comment]
I added the `.github` folder to the repo. Hope this help you guys get more details when people create issues or pull request.
