### ISSUE TITLE
Add user agent to HTTP requests

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/ios-sdk#201]
Include the SDK name and version. This enables the Watson team to track SDK usage.

Match how other SDKs define their user agent.

**Comment by germanattanasio** [comment]
value should be `watson-developer-cloud-ios-sdk-0.2.0` since we are using 0.2.0

**Comment by germanattanasio** [comment]
or 0.4.0 based on the milestone

**Comment by germanattanasio** [comment]
This is getting more important every day. Do we have a date for `0.4.0`? The milestone doesn't have ad ate yet.

**Comment by glennrfisher** [comment]
We don't have a good estimate of the date right now, but since this is important we can bump it up and accomplish it sooner. We'll move it to the 0.3.0 release and tackle it early among the set of issues.

**Comment by glennrfisher** [comment]
The way Alamofire sets the user-agent is helpful (see their code [here](https://github.com/Alamofire/Alamofire/blob/97df59cbd7a2e48c22423a59fdb4672aeea9ee24/Source/Manager.swift#L57)).

We may want to do something similar, but prefix the user-agent with `watson-developer-cloud-ios-sdk-0.2.0`.

**Comment by germanattanasio** [comment]
I think we can drop the `sdk` from the name: `watson-developer-cloud-ios-0.2.0`

**Comment by glennrfisher** [comment]
Just a note: we still need to add the user-agent in the `rest-kit` branch.

**Comment by glennrfisher** [comment]
Complete with eb5baa919334ec887676a60de71269da32954fb0
