### ISSUE TITLE
[general-sdk] check architectures for submission to app store

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/ios-sdk#208]
We need to investigate the architectures that are built and make sure they match the requirements for applications submitted to the app store.

https://developer.ibm.com/answers/questions/249027/ios-submition-issue-invalid-architectures/

![5545-screen-shot-2016-01-18-at-125053](https://cloud.githubusercontent.com/assets/1957636/13897808/7b917e04-ed8c-11e5-8341-4a37786081a3.png)

**Comment by sinchan** [comment]
@glennrfisher Hey, did you guys figure out how to fix this issue? We're trying to submit to the app store and getting the same errors.

**Comment by glennrfisher** [comment]
Hi @sinchan. Unfortunately, we have not yet gotten the chance to check out this issue. :(

**Comment by sinchan** [comment]
@glennrfisher Do you know if anyone has succeeded in submitting to the app store using recent versions of the SDK?

**Comment by glennrfisher** [comment]
According to [this Carthage issue](https://github.com/Carthage/Carthage/issues/353) this problem may have been caused by our "Copy Frameworks" build phase within the SDK project. I removed this build phase in the `remove-copy-frameworks` branch.

@sinchan: Would you mind building the SDK from the `remove-copy-frameworks` branch and try submitting to the app store again? We think this may fix the problem.

**Comment by sinchan** [comment]
@glennrfisher Just using the 'remove-copy-frameworks' branch didn't do it, but using it in addition to the following article and stackoverflow question did:

http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/
http://stackoverflow.com/questions/35240330/errors-building-xcode-project-after-adding-in-run-script-fatal-error-lipo-inpu

**Comment by glennrfisher** [comment]
Thanks for following up, @sinchan! Glad it's working.

You might also be interested in [this section](https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos) of the Carthage readme.
