### ISSUE TITLE
[text-to-speech] Add support for customizations

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/ios-sdk#219]
Add support for customizations. See: https://watson-api-explorer.mybluemix.net/apis/text-to-speech-v1
There are new endpoints like /v1/pronunciation and /v1/customizations

**Comment by glennrfisher** [comment]
Will do, thanks @germanattanasio!

**Comment by glennrfisher** [comment]
This is a duplicate of #229.
