### ISSUE TITLE
[alchemy-language] forced unwrapping causing crash on getRankedConcepts()

### ISSUE THREAD

**Issue by luish** [watson-developer-cloud/ios-sdk#228]
<img width="956" alt="screen shot 2016-04-08 at 09 18 38" src="https://cloud.githubusercontent.com/assets/133780/14378041/e89723da-fd6a-11e5-94ff-b33522c9f536.png">

[WatsonDeveloperCloud/AlchemyLanguage/AlchemyLanguage.swift#L398](https://github.com/watson-developer-cloud/ios-sdk/blob/24716008cf0347a3aceb40ffcaf9c89e144d24a2/WatsonDeveloperCloud/AlchemyLanguage/AlchemyLanguage.swift#L398)

Anyone else with the same issue?
I will try to get more info on how to reproduce this issue. It happens quite random.

**Comment by glennrfisher** [comment]
This will get fixed with the re-implementation of AlchemyLanguage in the `rest-kit` branch. We are being diligent with our reimplementations to avoid force unwrapping optionals.
