### ISSUE TITLE
Package Manager requires the folder Sources instead of Source

### ISSUE THREAD

**Issue by vherrin** [watson-developer-cloud/ios-sdk#235]
By convention, a package includes any source files located in the Sources/ directory.

https://swift.org/package-manager/#example-usage

**Comment by glennrfisher** [comment]
Good catch!

**Comment by glennrfisher** [comment]
Closing in favor of #120. (Using `swift build --init` will create a folder called `Sources` instead of `Source`, thereby addressing this issue.)
