### ISSUE TITLE
[alchemy-vision] add identity tag to ImageFaceTags

### ISSUE THREAD

**Issue by kognate** [watson-developer-cloud/ios-sdk#240]
in AlchemyVision,  if I call recognizeFaces() i get back ImageFaceTags but those do not include the identity of the faces.  I can get the identity tag from getRankedImageFaceTags, which is called in recognizeFaces.

**Comment by vherrin** [comment]
Thanks kognate for pointing this out!  A quick look shows some missing items in the models.  Should be a quick fix if you want to tackle it or we can get to it soon.

**Comment by kognate** [comment]
I'm happy to add it.  This was originally pointed out 

https://developer.ibm.com/answers/questions/267820/how-to-get-identity-when-using-alchemyvisionrecogn.html

that came through our slack from OM last night.

**Comment by glennrfisher** [comment]
This was tackled in our migration to the `rest-kit` architecture and is fixed with the most recent release.
