### ISSUE TITLE
Migrate AlchemyLanguage to RestKit

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/ios-sdk#244]
The `rest-kit` branch has a number of architectural changes that should make the SDK easier to maintain in the long-term. In particular, it:

1. Uses Alamofire directly instead of NetworkUtils or WatsonGateway.
2. Uses Freddy instead of ObjectMapper, allowing us to better express the models.
3. Uses separate `failure` and `success` closures to avoid unwrapping optionals and enable consistent error handling.

The process of migrating a service to RestKit requires a large re-implementation of the service. As part of the reimplementation, we additionally gain:

1. More consistent coding patterns between services.
2. Better documentation.
3. Better tests.
4. Reorganized project structure to support Swift Package Manager.

**Comment by Hsaylor** [comment]
Added with #297
