### ISSUE TITLE
Building scheme "Alamofire iOS" in Alamofire.xcworkspace ** BUILD FAILED **

### ISSUE THREAD

**Issue by amitds** [watson-developer-cloud/ios-sdk#250]
I am facing below build failed issue when I try to run "carthage update --platform iOS" command.

*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal arm64 /Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Timeline.swift
	CompileSwift normal arm64 /Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Upload.swift
	CompileSwift normal arm64 /Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/ParameterEncoding.swift
	CompileSwift normal arm64 /Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Request.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(5 failures)
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Request.swift:505:17: error: expected expression in list of expressions
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Request.swift:504:51: error: expected ',' separator
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Request.swift:505:17: error: expected ')' in expression list
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Request.swift:505:25: error: expected identifier in protocol declaration
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/ResponseSerialization.swift:34:5: error: expected declaration
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:736:32: error: expected expression after operator
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:736:117: error: braced block of statements is an unused closure
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:742:18: error: expected pattern
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:742:18: error: expected ':' after 'case'
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:742:18: error: expected expression
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:744:18: error: expected pattern
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:744:18: error: expected ':' after 'case'
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:744:18: error: expected expression
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:746:18: error: expected pattern
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:746:18: error: expected ':' after 'case'
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:746:18: error: expected expression
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:748:18: error: expected pattern
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:748:18: error: expected ':' after 'case'
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:748:18: error: expected expression
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Request.swift:505:17: error: expected expression in list of expressions
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Request.swift:504:51: error: expected ',' separator
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Request.swift:505:17: error: expected ')' in expression list
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Request.swift:505:25: error: expected identifier in protocol declaration
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/ResponseSerialization.swift:34:5: error: expected declaration
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:736:32: error: expected expression after operator
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:736:117: error: braced block of statements is an unused closure
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:742:18: error: expected pattern
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:742:18: error: expected ':' after 'case'
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:742:18: error: expected expression
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:744:18: error: expected pattern
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:744:18: error: expected ':' after 'case'
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:744:18: error: expected expression
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:746:18: error: expected pattern
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:746:18: error: expected ':' after 'case'
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:746:18: error: expected expression
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:748:18: error: expected pattern
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:748:18: error: expected ':' after 'case'
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:748:18: error: expected expression
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Request.swift:505:17: error: expected expression in list of expressions
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Request.swift:504:51: error: expected ',' separator
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Request.swift:505:17: error: expected ')' in expression list
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Request.swift:505:25: error: expected identifier in protocol declaration
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/ResponseSerialization.swift:34:5: error: expected declaration
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:736:32: error: expected expression after operator
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:736:117: error: braced block of statements is an unused closure
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:742:18: error: expected pattern
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:742:18: error: expected ':' after 'case'
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:742:18: error: expected expression
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:744:18: error: expected pattern
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:744:18: error: expected ':' after 'case'
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:744:18: error: expected expression
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:746:18: error: expected pattern
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:746:18: error: expected ':' after 'case'
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:746:18: error: expected expression
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:748:18: error: expected pattern
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:748:18: error: expected ':' after 'case'
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:748:18: error: expected expression
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Request.swift:505:17: error: expected expression in list of expressions
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Request.swift:504:51: error: expected ',' separator
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Request.swift:505:17: error: expected ')' in expression list
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Request.swift:505:25: error: expected identifier in protocol declaration
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/ResponseSerialization.swift:34:5: error: expected declaration
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:736:32: error: expected expression after operator
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:736:117: error: braced block of statements is an unused closure
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:742:18: error: expected pattern
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:742:18: error: expected ':' after 'case'
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:742:18: error: expected expression
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:744:18: error: expected pattern
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:744:18: error: expected ':' after 'case'
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:744:18: error: expected expression
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:746:18: error: expected pattern
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:746:18: error: expected ':' after 'case'
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:746:18: error: expected expression
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:748:18: error: expected pattern
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:748:18: error: expected ':' after 'case'
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Manager.swift:748:18: error: expected expression
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/ResponseSerialization.swift:113:39: error: 'SerializedObject' is not a member type of 'T'
/Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Request.swift:502:55: error: missing argument for parameter 'protocol' in call
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Alamofire.xcworkspace -scheme Alamofire iOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal arm64 /Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Timeline.swift
	CompileSwift normal arm64 /Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Upload.swift
	CompileSwift normal arm64 /Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/ParameterEncoding.swift
	CompileSwift normal arm64 /Users/admin/Desktop/WatsonSpeak/Carthage/Checkouts/Alamofire/Source/Request.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(5 failures)
![screen shot 2016-05-17 at 4 07 12 pm](https://cloud.githubusercontent.com/assets/13151104/15319634/75cd1bd6-1c49-11e6-8310-6ad7d2ee9097.png)

**Comment by glennrfisher** [comment]
Hmm. I tried this on my machine and did not run into any errors during the build. Are you running the most recent version of Xcode?

Unfortunately, changes were made to Alamofire 3.3.0+ that require Xcode 7.3+. If that's causing the problem, here are two alternatives you could try:

1. Upgrade Xcode to the most recent version, **or**
2. Add `github "Alamofire/Alamofire" == 3.2.1` to your Cartfile, which requires Carthage to use a version of Alamofire with Xcode 7.2 compatibility.

**Comment by amitds** [comment]
I upgraded my mac with OSX EI Capitan and xCode 7.3 and it worked now. Thanks.

**Comment by glennrfisher** [comment]
Great! Glad it worked. Thanks for the update.

**Comment by tbass134** [comment]
I'm having this issue when trying to build for xCode 8. I've tried forking this repo and updating the cart file to point to branches that support swift 2.3
```
 github "Alamofire/Alamofire" "swift2.3"
github "bignerdranch/Freddy" "zwaldowski/swift-2_3"
github "tbass134/Starscream" "master"`
```

then, pointing my example project to my fork
`github "tbass134/ios-sdk"`

after running the carthage install from my example project, it still points  to the original branches 
```
*** Checking out Alamofire at "3.4.1"
*** Checking out Freddy at "2.1.0"
*** Checking out Starscream at "1.1.3"
*** Checking out ios-sdk at "v0.5.0"
```

where it should point to the branches I've specified in my forked cart file

```
*** Checking out Alamofire at "1ac83593aaea0bb31c5d22c86d5a2cf90498ee71"
*** Checking out Freddy at "81bda2e49d9569bc54a29d8bc93d5881bdd6faf3"
*** Checking out Starscream at "8b6ec5716a712d80760a5d348a06cc34ce0dae43"
```

this may be a carthage issue, but I'm not sure
