### ISSUE TITLE
[documentation] add readme info for Rest-kit updates

### ISSUE THREAD

**Issue by vherrin** [watson-developer-cloud/ios-sdk#256]
Update information for the following:
	
- [x] AlchemyLanguageV1	
- [x] AlchemyVisionV1
- [x] DialogV1
- [x] LanguageTranslationV2
- [x] NaturalLanguageClassifierV1	
- [x] PersonalityInsightsV2
- [x] SpeechToTextV1	
- [x] TextToSpeechV1
- [x] ToneAnalyzerV3
- [x] VisualRecognitionV3

**Comment by vherrin** [comment]
There are at least two more stock voices that need included

**Comment by glennrfisher** [comment]
We don't necessarily need to list the voices anymore, since the service no longer takes a string.

**Comment by vherrin** [comment]
This is true but if a curious person stumbles on the site and wonders what voices and languages are available then they can see in the readme vs finding it in blumix docs

**Comment by glennrfisher** [comment]
Sure. Maybe link to the docs then, so that we don't have to worry about our readme getting out of date?

**Comment by vherrin** [comment]
that might work but sometimes I do not like to be redirected but if it opens in a new tab then that works for me

**Comment by vherrin** [comment]
This task is now complete.  Please let me know if you see any issues!
