### ISSUE TITLE
[general-sdk] prepare to merge `rest-kit` to `master`

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/ios-sdk#258]
The following items need to be addressed before the `rest-kit` branch is ready to be merged into `master`.

General:
- [x] Convert json.array(...).map to json.arrayOf(...)
- [x] Mode models outside of extensions
- [x] Update copyright to 2016
- [x] Create separate release and test targets for each service
- [x] Add spaces between `:Type`
- [x] Remove "\(string)" where unnecessary in NSURLQueryItems
- [x] Remove any print statements
- [x] Test with a sample application (this is esp. important because of the targets!)
- [x] Check that all files contain a copyright header (esp. the new .h files for each target)
- [x] Remove version information from all service signatures
- [x] Check all models for an init comment
- [x] Check all classes for an init comment
- [x] Update all error domains to reflect their target
- [x] Merge `master` into `rest-kit`, resolve any merge conflicts, and clean up the ensuing mess.

RestKit:
- [x] Fix errorWithCode deprecation
- [x] Create issue to rename and move RestKit to the MIL organization

Freddy:
- [x] Create an issue to add extensions to Freddy (i.e. PR). Keep open until PR accepted.

Speech to Text:
- [x] Use an enum in WordConfidence and WordTimestamp to get rid of magic numbers
- [x] Avoid silent failures if serializeString() throws (i.e. call failure function)

Visual Recognition:
- [x] Change `ClassWithExamples` to `Class`
- [x] Change `FaceImages` to `ImagesWithFaces`
- [x] Change `WordImages` to `ImagesWithWords`
- [x] Remove TODO on line 53 of WordImages
- [x] Create an issue: "[visual-recognition] add negative tests and dataToError function"
- [x] Remove external names
- [x] Remove unnecessary helper functions for detectFaces() and recognizeText()
- [x] Create an issue: "[visual-recognition] update testing resources to match documentation"

Text To Speech:
- [x] Remove TODO on line 230
- [x] Update tests
- [x] Merge to `rest-kit` branch

Alchemy Vision:
- [x] Create an issue: "[alchemy-vision] investigate HTML endpoints"
- [x] Create issue: "[alchemy-vision]: verify test results"
- [x] Create issue: "[alchemy-vision]: add negative tests and dataToError function"

Tone Analyzer:
- [x] Review for correctnes and style
- [x] Create issue: "[tone-analyzer]: verify test results"

**Comment by glennrfisher** [comment]
I wrote a quick sample application to test the `rest-kit` branch. In particular, I want to make sure that Carthage can locate all of the targets, build them (without code signing issues), and use them in an application.

The test app works perfectly on my local machine, but it would be helpful to get someone else on the team to try it. This well help make sure that there aren't any awkward issues with the code signing configuration of the new service targets.

To run the sample application:
1. Download and unzip the compressed file linked below.
2. Run `carthage update --platform iOS` in the `RestKitTestApp` directory.
3. Open the application and run the tests.

[RestKitTestApp.zip](https://github.com/watson-developer-cloud/ios-sdk/files/274116/RestKitTestApp.zip)

**Comment by glennrfisher** [comment]
I merged the `master` branch into `rest-kit`, resolved the merge conflicts, and double-checked the directory structure. I'll open a PR to merge the `rest-kit` branch to `master`, which we should be able to do without any conflicts now.

**Comment by glennrfisher** [comment]
Anybody remember what the "Remove external names" change was for Visual Recognition? I can't remember what it referred to and don't see any glaring issues with Visual Recognition.

**Comment by vherrin** [comment]
wasn't that the external and internal named parameters where one could be removed?

**Comment by vherrin** [comment]
carthage worked for me and I was able to run the tests

**Comment by Hsaylor** [comment]
Carthage and the test app seem to work for me as well

**Comment by glennrfisher** [comment]
Yes! Thanks. Forgot about the forced external parameter names. Thanks for the reminder! I fixed that with commit 20e07a7362323a81a1babd7c142cd15a034312f3.

Great to hear that the test application works for you both!

**Comment by glennrfisher** [comment]
Closing this issue since all tasks in the checklist have been completed.
