### ISSUE TITLE
Integrate CodeCov for test coverage reporting

### ISSUE THREAD

**Issue by milbuild** [watson-developer-cloud/ios-sdk#3]

**Comment by rfdickerson** [comment]
Added to the build script:

```yml
script:
- xctool -scheme WatsonDeveloperCloud build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
```

**Comment by vherrin** [comment]
Moved back to below which works.  Thanks for getting this running Robert!

- xcodebuild clean build test -scheme WatsonDeveloperCloud -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.1' -enableCodeCoverage YES
