### ISSUE TITLE
Record and publish introductory video

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/ios-sdk#301]
Record and publish a video that shows off some of the SDK's capabilities. This should be similar to the presentation that I gave to the Watson Technical Deep Dive call, but tailored to new SDK users and updated for the RestKit architecture.

**Comment by glennrfisher** [comment]
[ ] Outline
[ ] Create playground / workspace / example project
[ ] Create presentation
[ ] Record screen capture
[ ] Record voice over
[ ] Edit together
[ ] Publish
[ ] Post example

**Comment by thomaspaulmann** [comment]
Mmh... Example ;-)
