### ISSUE TITLE
Remove profiles for unit test Language Translation service

### ISSUE THREAD

**Issue by vherrin** [watson-developer-cloud/ios-sdk#308]
UserInfo={NSLocalizedFailureReason=number of allowed profiles per service (=10) exceeded}

Some of the unit tests are failing because of the exceeded limit

**Comment by glennrfisher** [comment]
This is fixed in #329 with [this function](https://github.com/watson-developer-cloud/ios-sdk/blob/ba651b8d5514ca1459f60a57f49f85877e0e448d/Source/LanguageTranslationV2/Tests/LanguageTranslationTests.swift#L50).
