### ISSUE TITLE
[Speech To Text API] How can i change the audio input to another Language?

### ISSUE THREAD

**Issue by fernandomatheus** [watson-developer-cloud/ios-sdk#317]
I'm using the speech to text service but by default it is with audio in English, how can i change to another language?

**Comment by glennrfisher** [comment]
You can change the language by setting the `model` property of the `TranscriptionSettings` object.

For example, the following code will transcribe broadband WAV data for Brazilian Portuguese:

```swift
import SpeechToTextV1

let speechToText = SpeechToText(username: "<your-username-here>", password: "<your-password-here>")

let settings = TranscriptionSettings(contentType: .WAV)
settings.model = `pt-BR_BroadbandModel`

let failure = { (error: NSError) in print(error) }

speechToText.transcribe(data, settings: settings, failure: failure) { results in
    print(results)
}
```

The [documentation](https://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/speech-to-text/input.shtml#models) includes information about the supported languages and models.

Hope that helps! Let me know if you have any other questions.
