### ISSUE TITLE
Optimize tests

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/ios-sdk#318]
Many of our tests take a long time to execute or seem nondeterministic (they sometimes work but sometimes fail). It would be good to improve our tests so that they take less time and are more consistent.

In particular, our tests make it hard to rely on the Travis build output. Often a test or set of tests will fail to execute successfully when run with Travis. That not only prevents us from knowing the state of our code, it also generates unhelpful comments from CodeCov.

(The weird thing with tests like that is that they will execute successfully when run locally, or perhaps individually.)

**Comment by thomaspaulmann** [comment]
Does it make sense to abstract the REST services with an Protocol and mock/stub them for Tests? Maybe we can investigate that together with the [Kitura-Request](https://github.com/IBM-Swift/Kitura-Request). 

If we can mock the requests we have some advantages like:

- Do not rely on an Internet Connection
- Much faster Tests
- More "predictable" Tests

Of course there are also some points to consider, for example:

- Mocking every REST Request or at least the Response 
- Keep the Responses up to date to match real-life Server Responses

It would mean also some changes to the Architecture. I don't no exactly if that helps, but I let it here :-)

**Comment by glennrfisher** [comment]
I have mixed feelings about this. On the one hand, as you say, it would make our tests faster, more predictable, and deterministic. But by doing so, we would no longer have as many integration tests connecting to live services.

I think it's important that we test against the live services. It often helps us catch bugs in the SDK as conditions change over time or services are updated. It's also a helpful way to test the services themselves--we've occasionally found bugs in the services as tests that once passed started to fail.

I think there are a lot of things we can try that will speed up the tests. I'm tempted to try improving the current tests before spending effort on a mock/stub solution.

But maybe in the future, when Watson has added more services and our tests start to take many minutes to run, we'll become frustrated, return to your comment, and wonder why we didn't just listen to you in the first place. ;)

**Comment by thomaspaulmann** [comment]
I agree with you! The live services are really important for catching bugs and it's a lot of effort to make the mock/stub solution. Let's see what happen with the amount of services as well as the duration of the tests.

**Comment by glennrfisher** [comment]
#### General Notes

- Sometimes receive a "network connection was lost" error that fails a test.
- Reducing the timeouts can speed-up the test time when there are failures.

#### AlchemyDataNewsV1Tests

- Tests run quickly. No need to modify them.
- Timeout: 5.0s

#### AlchemyLanguageV1Tests

- The tests seem to run consistently.
- The tests do not take an unreasonable amount of time.
- There are some tests on the order of 0.5s-1s that might be improvable.
- Overall, this test suite requires about 15 seconds to complete.
- Timeout: 5.0s

#### AlchemyVisionV1Tests

- The tests are _not_ running consistently.
  - `testGetRankedImageSceneTextImage`: varies between 3s and timing out.
- The tests do not take an unreasonable amount of time, but longer than necessary.
- Some tests require 1s-5s, and could probably be improved.
  - `testGetRankedImageFactTagsImage1`: 2.911s
  - `testGetRankedImageFaceTagsImage2`: 4.255s
  - `testGetRankedImageFaceTagsImageWithoutIdentity`: 5.202s
  - `testGetRankedImageFaceTagsURL1`: 4.512s
  - `testGetRankedImageFaceTagsURL2`: 3.978s
  - `testGetRankedImageKeywordsImage1`: 1.636s
  - `testGetRankedImageKeywordsImage2`: 1.629s
- Timeout: 10.0s

#### ConversationV1ExperimentalTests

#### DialogV1Tests

#### DocumentConversionV1Tests

#### LanguageTranslatorV2Tests

#### NaturalLanguageClassifierV1Tests

#### PersonalityInsightsV2Tests

#### RelationshipExtractionV1BetaTests

#### SpeechToTextV1Tests

#### TextToSpeechV1Tests

#### ToneAnalyzerV1Tests

#### TradeoffAnalyticsV1Tests

#### VisualRecognitionV3Tests

**Comment by glennrfisher** [comment]
We made a lot of improvements to the tests. I think they are running as smoothly and consistently as we can without mocking/stubbing the responses. Unfortunately, they still suffer from service changes and inconsistent network response times. As a result, we will probably look at stubbing the responses with [OHHTTPStubs](https://github.com/AliSoftware/OHHTTPStubs) soon.
