### ISSUE TITLE
Fix Travis builds for pull requests

### ISSUE THREAD

**Issue by Hsaylor** [watson-developer-cloud/ios-sdk#322]
Currently Travis fails any external pull request. We hadn't realized it since all of our feature branches were within the repo. This needs to be fixed so pull requests can be properly tested.

**Comment by Hsaylor** [comment]
#321 can be rerun to test

**Comment by thomaspaulmann** [comment]
@hsaylor: Thanks for creating the issue. I've you need more help with that, please let me know.

**Comment by glennrfisher** [comment]
I'm confused why the builds are failing. I don't see any specific errors in the log. Does anyone know what is causing the error?

As was mentioned, the log for #321's build contains the following warning but the same warning appears in our successful "internal" builds as well.

```
Warning: Failed to delete /Library/Caches/Homebrew.
Please do so manually.
```

(On a side-note, do we need to run `brew update && brew upgrade` with each PR? That must take a lot of time. Maybe we can track down the specific formulae that we need--if any--and only upgrade those?)

It's worth mentioning that our automated tests will not execute for "external" pull requests. According to the [Travis documentation](https://docs.travis-ci.com/user/pull-requests#Security-Restrictions-when-testing-Pull-Requests) the encrypted credentials file is not made available for "external" pull requests. Not only will the tests not run, but the build may fail if there is no `Credentials.plist` file.

**Comment by glennrfisher** [comment]
As far as I can tell, the `.travis.yml` file only calls `brew update` instead of `brew upgrade`. I don't think `brew update` actually modifies any of the brews, so we should be able to delete lines 15 and 16.

https://github.com/watson-developer-cloud/ios-sdk/blob/master/.travis.yml#L15

**Comment by Hsaylor** [comment]
So don't be fooled into thinking that's actually stopping the builds. That same waring appears in builds that pass. There's actually no error message which is one of the frustrating parts of this whole situation

**Comment by thomaspaulmann** [comment]
@glennrfisher , @Hsaylor Thanks for the informations!
It sounds like a weird behaviour from Travis. Furthermore I've found no workaround for the security issue of external PRs on Travis CI. Did you find something @glennrfisher ? The only thing that come up to mind would be to include the external developers to the organisation and give them limited (minimal) permissions. 

Anyways... How should we proceed with the open PR ( #316 #320 ) that rely on this issue?

**Comment by germanattanasio** [comment]
You just need to use the Travis environment variables to decide if you want to run the integration tests or not.
We do that in the java-sdk: https://github.com/watson-developer-cloud/java-sdk/blob/master/.travis.yml

Travis runs two jobs on pull requests one of them is on the potential changes from that pull request if it was merge. That's the one that will run the unit + integration tests.

I think we do this also in the node-sdk.

**Comment by glennrfisher** [comment]
This issue is a catch-22. On the one hand, we want all pull requests to be tested completely, including integration tests that connect to each service. But at the same time, we don't want to expose our encrypted credentials...

I don't think there's a good solution here so I'm going to close the issue.
