### ISSUE TITLE
[alchemy-vision] Optional Identity in FaceTags

### ISSUE THREAD

**Issue by thomaspaulmann** [watson-developer-cloud/ios-sdk#334]
The [Identity](https://github.com/watson-developer-cloud/ios-sdk/blob/master/Source/AlchemyVisionV1/Models/FaceTags.swift#L66) Property in the `ImageFace` of the `FaceTags` is not optional. This collides with the Documentation of the Service that describes the `Identity` as optional. 
The App is currently throwing an Deserialisation Error for an photo with an detected Face but not an appropriated Identity of a Celebrity. 

I will fix that in a small PR which should be included in the Release 0.4 (#330).

**Comment by glennrfisher** [comment]
Thanks! Complete with #336.
