### ISSUE TITLE
Carthage update fails with: Failed to discover shared schemes

### ISSUE THREAD

**Issue by shebbys** [watson-developer-cloud/ios-sdk#335]
My swift project use cocoapods... installed carthage today solely for use with watson.  Stuck at this step (same result if you remove --no-use-binaries).  XCode Version 7.3 (7D175).

carthage update --platform iOS --no-use-binaries
*** Fetching ios-sdk
*** Fetching Starscream
*** Fetching Freddy
*** Fetching Alamofire
*** Fetching ObjectMapper
*** Checking out Alamofire at "3.4.1"
*** Checking out Freddy at "2.1.0"
*** Checking out ObjectMapper at "1.3.0"
*** Checking out Starscream at "1.1.3"
*** Checking out ios-sdk at "v0.3.0"
*** Fetching AlamofireObjectMapper
*** Fetching SwiftHTTPStatusCodes
*** Fetching XCGLogger
Failed to discover shared schemes in project Alamofire.xcodeproj—either the project does not have any shared schemes, or xcodebuild never returned

If you believe this to be a project configuration error, please file an issue with the maintainers at https://github.com/Alamofire/Alamofire/issues/new

**Comment by glennrfisher** [comment]
Hmm. I ran `carthage update --platform iOS` and did not experience any errors. I've included my `Cartfile` and terminal output below. The `carthage version` command shows that I am using 0.16.2.

### Troubleshooting Steps

There are a few things you can try:
- Re-run the `carthage update --platform iOS` command.
- Delete the `Carthage` directory in your project folder.
- Update to the [most recent version](https://github.com/Carthage/Carthage/releases) of Carthage.
- Delete Carthage's cache: `rm -rf ~/Library/Caches/org.carthage.CarthageKit`

Hopefully one of those options will help. Let us know if you still have trouble.

### Cartfile

`github "watson-developer-cloud/ios-sdk"`

### Terminal Output

```
MacBook-Pro-3:test glennfisher$ carthage update --platform iOS
*** Fetching ios-sdk
*** Fetching Starscream
*** Fetching Freddy
*** Fetching Alamofire
*** Fetching ObjectMapper
*** Checking out Alamofire at "3.4.1"
*** Checking out ios-sdk at "v0.3.0"
*** Checking out Starscream at "1.1.3"
*** Checking out ObjectMapper at "1.3.0"
*** Checking out Freddy at "2.1.0"
*** xcodebuild output can be found in /var/folders/dg/zqb957lx6dq4hjhb80s7plvc0000gn/T/carthage-xcodebuild.xHmfN8.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "MobileFreddy" in Freddy.xcodeproj
*** Building scheme "ObjectMapper-iOS" in ObjectMapper.xcworkspace
*** Building scheme "Starscream" in Starscream.xcodeproj
*** Building scheme "SpeechToTextV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "RestKit" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "DialogV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "PersonalityInsightsV2" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "LanguageTranslationV2" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "AlchemyVisionV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "VisualRecognitionV3" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "TextToSpeechV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "NaturalLanguageClassifierV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "ToneAnalyzerV3" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "AlchemyLanguageV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "All Services" in WatsonDeveloperCloud.xcodeproj
```

**Comment by shebbys** [comment]
Thanks Glenn!  Turns out that brew installed version 0.11.  Compilation is
working with the latest carthage 17.1 installed.

**Comment by glennrfisher** [comment]
Excellent! Glad to hear it. :)

Feel free to open an issue if you ever have any questions/feedback/suggestions about the SDK!
