### ISSUE TITLE
Carthage hangs when following the Quick Start

### ISSUE THREAD

**Issue by dselman** [watson-developer-cloud/ios-sdk#342]
Following the Quick Start it seems like carthage hangs trying to build the dependent projects.

dselmans-MBP:MySpellings dselman$ carthage update --platform iOS
*** Fetching ios-sdk
*** Fetching Starscream
*** Fetching Freddy
*** Fetching Alamofire
*** Fetching ObjectMapper
*** Checking out Alamofire at "3.4.1"
*** Checking out ios-sdk at "v0.3.0"
*** Checking out ObjectMapper at "1.3.0"
*** Checking out Starscream at "1.1.3"
*** Checking out Freddy at "2.1.0"

--> Hang here, with no progress after 10 minutes. The only item in Checkouts is Alamofire.

I am using Xcode Version 7.3.1 (7D1014) and Carthage 0.17.1 installed using homebrew.

**Comment by glennrfisher** [comment]
Hmm. Unfortunately, I don't have any particular ideas on what could be the problem. :\

If Alamofire is the only project that's checked out, then maybe there was a problem with your network connection that caused it to hang? Or perhaps a problem with your Xcode configuration that caused the Alamofire build to hang?

You might find the troubleshooting steps in [this comment](https://github.com/watson-developer-cloud/ios-sdk/issues/335#issuecomment-228753640) to be helpful. I'm not sure if they will fix the problem, though.

We're looking forward to the Swift Package Manager with Swift 3.0. I think it will help to solve some of these problems, or at least create a larger user base and community for getting support.

P.S. A word of warning: the iOS SDK has a lot of targets and currently takes a long time to build.

**Comment by dselman** [comment]
I just tried this again from home (previously I was on the IBM network) and it worked!
** BUILD SUCCEEDED **
Very strange.

**Comment by glennrfisher** [comment]
Strange indeed. My IBM network connection seemed slow this morning...wonder if it's related. Very glad to hear that it worked, though! Feel free to open an issue if you have any questions/feedback/suggestions about the SDK.
