### ISSUE TITLE
Investigate speech-ios-sdk functionality

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/ios-sdk#343]
Investigate the functionality supported by the [speech-ios-sdk](https://github.com/watson-developer-cloud/speech-ios-sdk). We want to make sure that the iOS SDK at least matches all supported functionality.

Since the speech-ios-sdk has been deprecated, we would like to transition any remaining users to the iOS SDK. To do so, the iOS SDK should provide the same functionality. Ideally, the iOS SDK would have a better API or more functionality so that developers would _prefer_ to use it over the speech-ios-sdk.

Of particular note is #175. I believe the speech-ios-sdk compresses the audio to Opus to reduce the upload size. This is not yet supported in the iOS SDK. There are a number of outstanding speech-to-text issues that should also be reviewed.

Once we compare functionality we should report to @germanattanasio what matches, what's missing, related issues, and any plans to add support.

**Comment by germanattanasio** [comment]
This is a good point to start looking at use cases/functionality speech-ios-sdk#28

**Comment by glennrfisher** [comment]
I reviewed the speech-ios-sdk repository. The iOS SDK is currently missing support for the following features:

- Token Authentication (#327)
- Compress streaming audio (#175 / #183)
- Access raw microphone data (#390)
- Calculating the audio signal power (#389)

Each missing feature has an associated issue in our repository. They are included in the upcoming milestones. We hope to spend some time updating and and improving our implementation of Speech to Text, which will include support for all of these features.
