### ISSUE TITLE
Add support for Swift 3.0

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/ios-sdk#376]
Our understanding is that Swift 3.0 should be in a (relatively) stable preview state by July 27.

"The last day to take planned source-breaking changes for Swift 3 is July 27." -- https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20160711/024424.html

That would be a good time to start a `swift3` branch and transition the SDK to support Swift 3.0.

We should also examine many of the decisions that we made in the SDK. With so many changes for Swift 3.0, it would also be a good time to change features of the SDK. For example--do we like separate success and failure functions? how do users authenticate? is the RestKit serialization working well for us? are there any dependencies we should drop? do we want to change the API for any of the services?

**Comment by MatthewWaller** [comment]
Any word on when this might happen? Next few weeks? Months? Thanks!

**Comment by glennrfisher** [comment]
Yeah! Should be in the next few weeks. I think this is a high-priority issue that we should tackle in our next sprint (9/26 - 10/7). I'll be sure to advocate for it in our team's upcoming planning meeting.

**Comment by kteman** [comment]
Thanks I'll add my comment as well. Xcode 8 recommends by default updating all projects to Swift 3, and with this module not compiled in Swift 3 it is not possible to update the rest of the project to swift 3 (almost worse than the Objective-C to Swift transition because at least that allowed bridging headers). Looking forward to this as it pains me to not update to swift 3 immediately. Thanks.

**Comment by glennrfisher** [comment]
Thanks for your comment, @kteman. It's always good for us to hear about our users' experiences, and it's really helpful to hear that users are frustrated by the lack of Swift 3.0 support. This is more ammunition for me to try and prioritize Swift 3.0 support in our upcoming sprint. Thanks!

**Comment by kteman** [comment]
Thanks. It's pretty important to me as this is the only barrier for getting my project to Swift 3. I'm looking forward to making that transition sooner than later (like taking care of house cleaning, want to get it done).

**Comment by glennrfisher** [comment]
I want to give a quick update for anyone following this issue:

We made a lot of progress migrating the SDK to Swift 3.0. In the [`swift-3.0`](https://github.com/watson-developer-cloud/ios-sdk/tree/swift-3.0) branch we've been able to update the project settings and move all of our services to Swift 3.0 (with the exception of Speech to Text which requires some more work around the interfaces to C libraries).

There's still a lot of work to be done, though, before we feel comfortable publishing a release. In particular, we want to review the SDK and adhere to the [Swift 3.0 API Design Guidelines](https://swift.org/documentation/api-design-guidelines/). We expect a lot of changes to the API (mostly around parameter names).

Ideally, we would finish the Swift 3.0 migration by 10/7. But realistically, it will probably take another week or two since there are some important outstanding issues and user questions that we should address.

Be aware that the `swift-3.0` branch is still under active development--we expect a lot of changes over the coming week or two. If you want to live on the cutting-edge, you can specify the `swift-3.0` branch in your Cartfile (`github "watson-developer-cloud/ios-sdk" "swift-3.0"`), but expect breaking changes as we push new commits.

**Comment by glennrfisher** [comment]
The code builds and tests pass. We're reviewing PRs to rename the SDK methods according to the Swift 3.0 API Guidelines. Hope to get it released soon.

**Comment by troyibm** [comment]
sorry... I don't understand "PRs to rename the SDK methods according to the Swift 3.0 API Guidelines".  Pull Requests? I don't see any that rename methods.  Guess I need to google "Swift 3.0 API Guidelines".  Do you think the swift-3.0 branch is good enough to use in development as we don't want to go back to 2.3 when we need to use 3.0 for other libraries.

**Comment by glennrfisher** [comment]
We have migrated the SDK to Swift 3.0 and removed the Alamofire and Freddy dependencies in the `swift-3.0-remove-dependencies` branch. We'll be merging that branch to `master` and publishing a release today or Monday after updating the readme and tackling issue #510 with Visual Recognition.

Thanks for your patience, all. We've been doing our best to tackle issues and deliver, but the team here has been pulled in many different directions, causing some of these issues to take much longer than expected.

**Comment by MatthewWaller** [comment]
Thanks so much for y'all's work on this Glenn!

**Comment by horaciogarza** [comment]
Just for being secure myself 😏, I can use the `swift-3` branch right now? (I can't wait until monday)

**Comment by glennrfisher** [comment]
I would actually recommend the `swift-3-remove-dependencies` branch. It's a bit newer. The readme and quickstart guides have also been updated in that branch, in case you find them helpful.
