### ISSUE TITLE
Improve support for ending streaming

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/ios-sdk#388]
The SDK is prematurely closing the connection with [this line](https://github.com/watson-developer-cloud/ios-sdk/blob/master/Source/SpeechToTextV1/SpeechToTextAudioStreamer.swift#L145). We should change this so that the client sends a "stop" message then waits for the server to "listen" again. That way we know that all results have been sent to the user.

It would also be helpful if the user could know when they've received all of the results. Perhaps expose a property with the state of the WebSocket connection?

See [this question](https://developer.ibm.com/answers/questions/288513/watson-speech-to-text-where-can-i-find-or-get-and.html) for more context.

**Comment by mihui** [comment]
It depends. But you don't have to expose the state of connection in this case, might be useful for the other scenarios, e.g. keep alive connection and re-connect with service in case it is disconnected. Instead, close connection properly and in time will help, either from SDK or application. 

I am not sure how the StarScream behave when you're sending out the "stop" message meanwhile closing the connection, but it is not effective in SocketRocket WebSocket library that I'm using. 

Here is my discovery: 
- If set "continuous" parameter as true, you have to send out "stop" message and wait for the 2nd "listening" state, after that, close connection
- By default, "continuous" is false, or if you set it as false, you don't have to send out "stop" message, the server will eventually return "final" transcript, and the 2nd "listening" state will be returned, in this case, you can disconnect directly

Example of sending out the "stop" if "continuous" is set to true:
https://github.com/mihui/speech-ios-sdk/blob/master/watsonsdktest-objective-c/STTViewController.m#L100

Example of closing connection if (the 1st "listening" state is already returned previously (also means socket is connected), and the 2nd "listening" state is being returned) and ("continuous" is set to false, or the "stop" message has been written into the socket):
https://github.com/mihui/speech-ios-sdk/blob/master/watsonsdk/websocket/WebSocketAudioStreamer.m#L301

**Comment by glennrfisher** [comment]
Closing in favor of #405.
