### ISSUE TITLE
[text-to-speech][language-translation] Azerbaijani language has different language name identifiers in Model vs IdentifiableLanguage

### ISSUE THREAD

**Issue by jaalger** [watson-developer-cloud/ios-sdk#447]
Currently using the the TextToSpeech and LanguageTranslation services in Swift. When pulling a list of the IdentifiableLanguages I get the following for Azerbaijani:

LanguageTranslatorV2.IdentifiableLanguage(language: "az", name: "Azerbaijani")

As you can see the language short name is listed as "az"

When pulling a list of default models I see the following TranslationModels:

LanguageTranslatorV2.TranslationModel(modelID: "arz-en", name: "", source: "arz", target: "en", baseModelID: "", domain: "news", customizable: true, defaultModel: true, owner: "", status: LanguageTranslatorV2.TrainingStatus.Available)

LanguageTranslatorV2.TranslationModel(modelID: "en-arz", name: "", source: "en", target: "arz", baseModelID: "", domain: "news", customizable: true, defaultModel: true, owner: "", status: LanguageTranslatorV2.TrainingStatus.Available)

As you can see the language short name here for Azerbaijani is "arz".

When using LanguageTranslation and TextToSpeech I would assume that the language short names should be consistent across TranslationModels and IdentifiableLanguages

**Comment by glennrfisher** [comment]
Thanks, @jaalger! I shared this issue with the Language Translation team.

**Comment by glennrfisher** [comment]
I heard back from the Language Translation team, @jaalger: `arz` is for Egyptian Arabic, not Azerbaijani. Hope that helps to clear up any confusion!

**Comment by jaalger** [comment]
@glennrfisher There is still an issue then. There is no IdentifiableLanguage with the short name arz.  If you have a model that lists the language such as:

LanguageTranslatorV2.TranslationModel(modelID: "arz-en", name: "", source: "arz", target: "en", baseModelID: "", domain: "news", customizable: true, defaultModel: true, owner: "", status: LanguageTranslatorV2.TrainingStatus.Available)

LanguageTranslatorV2.TranslationModel(modelID: "en-arz", name: "", source: "en", target: "arz", baseModelID: "", domain: "news", customizable: true, defaultModel: true, owner: "", status: LanguageTranslatorV2.TrainingStatus.Available)

There should be a matching IdentifiableLanguage with short name arz. Here are the IdentifiableLanguages that begin with a:

[LanguageTranslatorV2.IdentifiableLanguage(language: "af", name: "Afrikaans"), LanguageTranslatorV2.IdentifiableLanguage(language: "ar", name: "Arabic"), LanguageTranslatorV2.IdentifiableLanguage(language: "az", name: "Azerbaijani"), 

I also grabbed a list of all  IdentifiableLanguages and did not see any listed as Egyptian Arabic

**Comment by glennrfisher** [comment]
Okay, thanks for clarifying @jaalger. I shared your thoughts with the language translation team and they are following up on it. I will let you know of any updates.

**Comment by jaalger** [comment]
Any update on this issue? I see it is closed, but I believe there is still an issue

**Comment by glennrfisher** [comment]
I messaged the language translation team on 9/16. The person I contacted reached out to a few other folks, but they did not respond. I just messaged them all again on Slack.

I do want to keep the issue closed--it's not really an issue for our SDK, but the service itself. You may have better luck posting on dWAnswers.
