### ISSUE TITLE
Compile errors with Xcode 8 after pulling the 0.8.0 binaries

### ISSUE THREAD

**Issue by troyibm** [watson-developer-cloud/ios-sdk#449]
I have specified release 0.8.0 in my Cartfile and I see this when I do a `carthage update`:
*** Downloading ios-sdk.framework binary at "Release 0.8.0"

But when I go into Xcode for my project, I see this error next to my `import SpeechToTextV1`:

Module file was created by an older version of the compiler; rebuild 'SpeechToTextV1' and try again: /Users/tdugger/git/Olli-iOS10/askOlli_iOS/Carthage/Build/iOS/SpeechToTextV1.framework/Modules/SpeechToTextV1.swiftmodule/x86_64.swiftmodule

Does this mean that for some reason the binaries you built for 0.8.0 weren't built with Xcode 8 and that means I have to download the source and build them instead?

/cc @glennrfisher

**Comment by glennrfisher** [comment]
Hey Troy! I should get a chance to look at this later today. It should have
been built with Xcode 8, though. Note that v0.8.0 uses Swift 2.3, not 3.0.
So you may need to switch your project to 2.3.

**Comment by troyibm** [comment]
Thanks Glenn.  Legacy Swift Version is set to true.

**Comment by glennrfisher** [comment]
Thanks, @troyibm! You were definitely right about the binaries having been built with Xcode 7. Even though I was developing in Xcode 8, I think I still had my command-line tools set to Xcode 7.

I updated the release with new binaries and tested them successfully in an Xcode 8 project with "use legacy Swift language version" set to Yes.

In case we need to refer to it later, here's the error that Xcode gives when trying to use a Swift 2.3 framework in a Swift 3.0 project. It's much more explicit than the error message when using pre-2.3 versions of Swift.

![screen shot 2016-09-15 at 7 59 44 pm](https://cloud.githubusercontent.com/assets/1957636/18572276/6a48eb88-7b7f-11e6-8526-28b9a62e4a62.png)
