### ISSUE TITLE
[Speech-to-Text] Add 'createTranscriptionOutput' to ios-sdk-0.8.0

### ISSUE THREAD

**Issue by asidd** [watson-developer-cloud/ios-sdk#454]
Client via Parature support ticket:

SpeechToText ios-sdk-0.6.0 has a function named 'createTranscriptionOutput' through which we were able to create new AVCaptureSession, so that we can save the microphone data and stream it to watson simultaneously .

We are unable to find replacement for the same function in ios-sdk-0.8.0.

**Comment by glennrfisher** [comment]
Hi, @asidd. I'm not sure if there's a better way for me to communicate with clients that use Parature, so I will respond to this GitHub issue.

We effectively did a rewrite of the iOS SDK's API and implementation for Speech to Text. There are many benefits to the new implementation: Opus encoding (significantly reduces latency and bandwidth), decibel power levels for the microphone, simple/advanced usage with the SpeechToText/SpeechToTextSession classes, and more. Many of these features were requested by our users and clients.

In the new implementation, we migrated from using `AVCaptureSession` to lower-level [audio queue services](https://developer.apple.com/library/content/documentation/MusicAudio/Conceptual/AudioQueueProgrammingGuide/Introduction/Introduction.html). This allows us to better control the microphone, access power level information, and should be faster. Unfortunately, that means we no longer support the `createTranscriptionOutput()` function that was included in previous releases.

The previous releases of the SDK will remain on GitHub, so you can continue to use v0.6.0 until you are ready to tackle the updates to the new Speech to Text implementation. For more information about the new implementation, including lots of sample code to help you get started, please see the [readme](https://github.com/watson-developer-cloud/ios-sdk#speech-to-text).
