### ISSUE TITLE
How to use Rank based search in iOS 

### ISSUE THREAD

**Issue by andrew21c** [watson-developer-cloud/ios-sdk#456]
I see there is a rank based search for AlchemyData News in doc 
http://docs.alchemyapi.com/docs/rank-based-search#

Is this supported in IOS SDK? Do you have any example on how to added rank parameter during swift query?

Thanks.

**Comment by glennrfisher** [comment]
Hi @andrew21c. Apologies for the delay--we usually try to respond to issues much faster, but have been very busy recently.

The `rank` query is supported with AlchemyData News. Just pass it in the `query` parameter of the `getNews` function. Here's some code that adapts the [readme](https://github.com/watson-developer-cloud/ios-sdk#alchemydata-news) to demonstrate the `rank` parameter.

```swift
import AlchemyDataNewsV1

let apiKey = "your-apikey-here"
let alchemyDataNews = AlchemyDataNews(apiKey: apiKey)
let failure = { (error: NSError) in print(error) }

let start = "now-1d" // yesterday
let end = "now" // today
let query = [
    "rank": "high"
]    

alchemyDataNews.getNews(start, end: end, query: query, failure: failure) { news in
    print(news)
}
```

Hope that helps! Let us know if you run into any trouble.

**Comment by andrew21c** [comment]
Thanks. This is very helpful.
