### ISSUE TITLE
Review text-to-speech-swift

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/ios-sdk#466]
We should review this sample application to make sure it is consistent with the other text-to-speech samples (particularly their readme):
- [text-to-speech-python](https://github.com/watson-developer-cloud/text-to-speech-python)
- [text-to-speech-java](https://github.com/watson-developer-cloud/text-to-speech-java)
- [text-to-speech-nodejs](https://github.com/watson-developer-cloud/text-to-speech-nodejs)

**Comment by schen22** [comment]
Updated [sample app](https://github.com/watson-developer-cloud/text-to-speech-swift)
