### ISSUE TITLE
Develop speech-to-text-swift

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/ios-sdk#468]
Let's create a sample application to demonstrate how to use the Speech to Text service in a Swift-based application.

**Comment by troyibm** [comment]
I wish this was part of Release 0.9.0.  Instead of updating the objective-c version, creating a Swift version would be more beneficial, since there is nothing.

**Comment by glennrfisher** [comment]
Hey @troyibm. We have some clients that want to consume the SDK in an Objective-C application. We were asked to focus on sample applications to help them understand how to consume a Swift-based SDK in an Objective-C application. This sample application is on our backlog and we will get to it eventually.

**Comment by glennrfisher** [comment]
We developed the [`speech-to-text-swift`](https://github.com/watson-developer-cloud/speech-to-text-swift) sample application yesterday. It was very helpful to test and debug our Swift 3.0 migration before the v0.9.0 release.
