### ISSUE TITLE
Need smart formatting param in recognizeer settings

### ISSUE THREAD

**Issue by dennisnotojr** [watson-developer-cloud/ios-sdk#507]
Speech to text has the ability to smart format numbers etc. this is a major need for Watson conversation service via voice. Please add per the API specification for smart_formating

Thanks Dennis, IBM Exec architect

**Comment by dennisnotojr** [comment]
Needed for several major client exec demonstrations

**Comment by vherrin** [comment]
This is a duplicate to #415 so closing
