### ISSUE TITLE
Update sample applications for Swift 3.0

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/ios-sdk#517]
The sample applications need to be updated to reflect the API changes that occurred in the migration to Swift 3.0.

**Comment by horaciogarza** [comment]
This will be awesome.

**Comment by glennrfisher** [comment]
Here are the commits / pull requests that update the sample applications for Swift 3.0:
- [Simple Chat (Objective-C)](https://github.com/watson-developer-cloud/simple-chat-objective-c/commit/7961efab3db163302375fd3daa137322569720ea)
- [Speech to Text](https://github.com/watson-developer-cloud/speech-to-text-swift/commit/7525d613516a94283df2073d71572deeb53cb44c)
- [Text to Speech](https://github.com/watson-developer-cloud/text-to-speech-swift/commit/2fba14ef1670b9e09ab1cfa904506fd983ce10c6)
- [Cognitive Concierge](https://github.com/IBM-MIL/CognitiveConcierge/pull/8)
