### ISSUE TITLE
Look into circle-ci as an alternative to Travis

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/ios-sdk#523]
I heard from different sources that [circle-ci](https://circleci.com/docs/ios-builds-on-os-x) has better support for iOS applications.

**Comment by vherrin** [comment]
Does not look like circle-ci has a free version

**Comment by germanattanasio** [comment]
You are right @vherrin :(

**Comment by glennrfisher** [comment]
It's pretty well-hidden, but it looks like it's possible to get access to a free version for open-source repositories.

![image](https://cloud.githubusercontent.com/assets/1957636/20108413/a0558384-a5a1-11e6-9e55-000795018fc2.png)

![screen shot 2016-11-08 at 10 54 06 am](https://cloud.githubusercontent.com/assets/1957636/20108445/b6aee5ee-a5a1-11e6-86b8-d7a6c6152fbd.png)

**Comment by vherrin** [comment]
can a linux container test iOS?

**Comment by glennrfisher** [comment]
The OS X Seed plan should be able to test iOS.
