### ISSUE TITLE
Alchemy Docs for HTMLGetImage displays incorrect URL

### ISSUE THREAD

**Issue by vherrin** [watson-developer-cloud/ios-sdk#56]
Documentation for HTMLGetImage has URL which gives 404 error
	http://gateway-a.watsonplatform.net/calls/url/HTMLGetImage

Located here 
	http://www.alchemyapi.com/api/image-link-extraction/htmlc.html

Java SDK has endpoint as /html/HTMLGetImage

**Comment by glennrfisher** [comment]
@germanattanasio: Looks like they haven't made any changes. Could you try reaching out to them again?

**Comment by germanattanasio** [comment]
@glennrfisher we are moving the documentation to our site and it will be fixed there.

**Comment by glennrfisher** [comment]
That's great. Thanks @germanattanasio!
