### ISSUE TITLE
Investigate WebSockets connection problem

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/ios-sdk#73]
Most connection requests are successfully upgraded to WebSockets. Some, however, fail to be upgraded. This is most likely a network communication problem or an issue with the Watson back-end. More investigation is required to pinpoint the problem.

**Comment by dsato80** [comment]
I found a bug in Starscream may relates to this problem and made a pull request.
https://github.com/daltoniam/Starscream/pull/154

**Comment by glennrfisher** [comment]
That's awesome, @dsato80! Looking forward to tracking your pull request and seeing if it helps us here, too.

**Comment by dsato80** [comment]
The issue was fixed in the Release 1.1.1!
https://github.com/daltoniam/Starscream/releases/tag/1.1.1

**Comment by kweinmeister** [comment]
@dsato80 Great news! If you are able, can you create a pull request to upgrade the dependency in the Watson project after you've tested it?

**Comment by dsato80** [comment]
I have tested and made a pull request #165

**Comment by glennrfisher** [comment]
Thanks again for the pull request, @dsato80!
