### ISSUE TITLE
[dialog] Fix time-zone bug

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/ios-sdk#91]
Ensure tests are written properly and successfully pass once the getConversations method is debugged.

**Comment by glennrfisher** [comment]
@vherrin: Any word from the Dialog team? I'll also follow-up in our email chain.

**Comment by glennrfisher** [comment]
Looks like the timestamp of the received conversation history is still 17 hours in the future. Waiting to hear from the Watson team about a resolution to the problem.

**Comment by glennrfisher** [comment]
This seems to be a problem with production environment VMs and probably won't be fixed anytime soon. I'll go ahead and change the `getConversations` method to adjust the time so that we can move forward on resolving this problem.

**Comment by glennrfisher** [comment]
Complete with 6fbf2c6b98c8ef2ee652f80cdf2d6e6a576de639

**Comment by sanjayko** [comment]
you can set/view the timezone for a particular dialog service
in the XML or applet in Account-->Settings 
and the dates you provide in this API endpoint are assumed to be in the same timezone 
so no need to specify timezone or worry about it in any way

**Comment by glennrfisher** [comment]
@sanjayko That's excellent to know, thank you!

It would be really helpful if the [Swagger documentation](https://watson-api-explorer.mybluemix.net/apis/dialog-v1#!/Conversation/getSessionData) was updated to note that assumption about the `date_from` and `date_to` parameters.

We'll back out the changes from 6fbf2c6 and add comments about the `date_from` and `date_to` arguments to make the timezone assumption clear to users of the SDK.

**Comment by sanjayko** [comment]
yes, Have requested the dialog and documentation team to update.

**Comment by glennrfisher** [comment]
Thanks, @sanjayko! We really appreciate that.

**Comment by glennrfisher** [comment]
Complete with 48317cba2319ad89c4b6599cf3ec727a14bf7caa
